# Generated by Django 3.0 on 2019-12-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=50)),
                ('ein_1', models.CharField(blank=True, max_length=6)),
                ('ein_2', models.CharField(blank=True, max_length=6)),
                ('ein_3', models.CharField(blank=True, max_length=6)),
                ('nid', models.CharField(blank=True, max_length=17)),
                ('amount', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
