# Generated by Django 3.0 on 2019-12-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nid',
            field=models.CharField(blank=True, max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
